// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: encryptor.proto

package encryptorapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Encryptor_Encrypt_FullMethodName = "/encryptorapi.Encryptor/Encrypt"
)

// EncryptorClient is the client API for Encryptor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncryptorClient interface {
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
}

type encryptorClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptorClient(cc grpc.ClientConnInterface) EncryptorClient {
	return &encryptorClient{cc}
}

func (c *encryptorClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, Encryptor_Encrypt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptorServer is the server API for Encryptor service.
// All implementations must embed UnimplementedEncryptorServer
// for forward compatibility
type EncryptorServer interface {
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	mustEmbedUnimplementedEncryptorServer()
}

// UnimplementedEncryptorServer must be embedded to have forward compatible implementations.
type UnimplementedEncryptorServer struct {
}

func (UnimplementedEncryptorServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedEncryptorServer) mustEmbedUnimplementedEncryptorServer() {}

// UnsafeEncryptorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncryptorServer will
// result in compilation errors.
type UnsafeEncryptorServer interface {
	mustEmbedUnimplementedEncryptorServer()
}

func RegisterEncryptorServer(s grpc.ServiceRegistrar, srv EncryptorServer) {
	s.RegisterService(&Encryptor_ServiceDesc, srv)
}

func _Encryptor_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptorServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Encryptor_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptorServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Encryptor_ServiceDesc is the grpc.ServiceDesc for Encryptor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Encryptor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "encryptorapi.Encryptor",
	HandlerType: (*EncryptorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _Encryptor_Encrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encryptor.proto",
}
